spring:
  application:
    name: url-analyzer-service

  kafka:
    bootstrap-servers: kafka:9092

external-api:
  authServiceUrl: "gateway:8080/api/v1/auth"
  playwrightServiceUrl: "gateway:8080/api/v1/playwright"

app:
  kafka:
    kafkaEventTopic: user-registration-event-topic
    kafkaEventGroupId: user-registration-event-group-id

eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/